import { inter } from '@/app/ui/fonts';
import type { Metadata } from 'next';
import './globals.css';
import NavLinks from './ui/NavLinks';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
              <NavLinks />
              {children}
              </body>
        </html>
    );
}
